
static const char* main_html = "<!DOCTYPE html>\n"
"<html>\n"
"<head>\n"
"    <meta charset=\"utf-8\">\n"
"    <title>Banker's Algorithm GUI</title>\n"
"    <style>\n"
"        body { font-family: Arial, sans-serif; padding: 20px; background: #f5f5f5; }\n"
"        .panel { background: white; padding: 15px; margin: 10px 0; border-radius: 6px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }\n"
"        h2 { color: #2c3e50; margin-top: 0; }\n"
"\n"
"        .resource-bar {\n"
"            height: 20px;\n"
"            background: #eee;\n"
"            border-radius: 10px;\n"
"            overflow: hidden;\n"
"            margin: 5px 0;\n"
"        }\n"
"        .resource-fill {\n"
"            height: 100%;\n"
"            background: #3498db;\n"
"            border-radius: 10px;\n"
"            transition: width 0.3s ease;\n"
"        }\n"
"\n"
"        /* Process styles */\n"
"        .process { margin: 8px 0; padding: 8px; background: #ecf0f1; border-left: 4px solid #3498db; }\n"
"        .waiting { border-left-color: #e67e22; }\n"
"        .running { border-left-color: #2ecc71; }\n"
"        .finished { border-left-color: #95a5a6; }\n"
"    </style>\n"
"</head>\n"
"<body>\n"
"<h2>Resource Simulator GUI</h2>\n"
"\n"
"<div class=\"panel\">\n"
"    <h3>Resource Availability</h3>\n"
"    <div id=\"resources\"></div>\n"
"</div>\n"
"\n"
"<div class=\"panel\">\n"
"    <h3>Process Status</h3>\n"
"    <div id=\"processes\"></div>\n"
"</div>\n"
"\n"
"<div id=\"completion\" style=\"display:none; color:#27ae60; font-weight:bold;\">\n"
"    Simulation completed successfully\n"
"</div>\n"
"\n"
"<script>\n"
"    function update() {\n"
"        fetch('/state')\n"
"            .then(r => r.json())\n"
"            .then(data => {\n"
"                // Resources\n"
"                let rHtml = '';\n"
"                for (let i = 0; i < data.resources.length; i++) {\n"
"                    const pct = (data.resources[i] / data.max[i]) * 100;\n"
"                    rHtml += `\n"
"              <div>Resource ${i}: ${data.resources[i]}/${data.max[i]}</div>\n"
"              <div class=\"resource-bar\">\n"
"                <div class=\"resource-fill\" style=\"width: ${pct}%\"></div>\n"
"              </div>`;\n"
"                }\n"
"                document.getElementById('resources').innerHTML = rHtml;\n"
"\n"
"                // Processes\n"
"                let pHtml = '';\n"
"                data.processes.forEach(p => {\n"
"                    const cls = p.status.toLowerCase();\n"
"                    pHtml += `\n"
"              <div class=\"process ${cls}\">Process ${p.id}: <b>${p.status}</b> (request: [${p.req}])</div>`;\n"
"                });\n"
"                document.getElementById('processes').innerHTML = pHtml;\n"
"                let allFinished = data.processes.every(p => p.status === \"Finished\");\n"
"                document.getElementById('completion').style.display = allFinished ? 'block' : 'none';\n"
"            });\n"
"    }\n"
"\n"
"    update();\n"
"    setInterval(update, 100);\n"
"</script>\n"
"</body>\n"
"</html>\n";